export const mineralColors = [
  "Yellow",
  "Orange",
  "Black",
  "Blue",
  "Bluish-green",
  "Brown",
  "Cream",
  "Green",
  "Greenish-blue",
  "Grey",
  "Pale brown",
  "Pink",
  "Purple",
  "Red-brown",
  "Red",
  "Violet",
  "Yellow-orange"
];

export const mineralSystems = [
  "Triclinic",
  "Monoclinic",
  "Orthorhombic",
  "Hexagonal",
  "Tetragonal",
  "Trigonal",
  "Isometric"
];

export const mineralGroups = [
  "Elements",
  "Sulfides",
  "Sulfosalts",
  "Halides",
  "Oxides",
  "Carbonates",
  "Nitrates",
  "Borates",
  "Sulfates",
  "Phosphates",
  "Arsenates",
  "Vanadates",
  "Silicates",
  "Organic Compounds"
];

export const mineralSubGroups = [
  "Metals",
  "Metalloids",
  "Nonmetals",
  "Carbides",
  "Silicides",
  "Nitrides",
  "Phosphides",
  "Selenides",
  "Tellurides",
  "Arsenides",
  "Antimonides",
  "Bismuthides",
  "Sulfarsenites",
  "Sulfantimonites",
  "Sulfbismuthies",
  "Oxysulfosalts",
  "Complex Halides",
  "Oxyhalides",
  "Hydroxyhalides",
  "Iodates",
  "Nitrates",
  "Monoborates",
  "Diborates",
  "Triborates",
  "Tetraborates",
  "Pentaborates",
  "Hexaborates",
  "Heptaborates",
  "Chromates",
  "Uranyl sulfates",
  "Molybdates",
  "Wolframates",
  "Niobates",
  "Nesosilicates",
  "Sorosilicates",
  "Cyclosilicates",
  "Inosilicates",
  "Phyllosilicates",
  "Tektosilicates",
  "Germanates",
  "Unclassified"
];
