name: Deploy to Google App Engine
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: v1

      - name: Set project id
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}
      - name: Deploy to App Engine
        run: gcloud app deploy --quiet
